#!/bin/bash

if [ "$EUID" -ne 0 ]; then echo "Run it with root | Root ile çalıştırınız"

apt install linux-image-6.12.31-amd64
apt remove --autoremove --purge linux-image-6.12.57+deb13-amd64
apt remove --autoremove --purge linux-image-6.12.63+deb13-amd64

echo "Kernel has been swapped succesfully | Çekirdek başarıyla değiştirildi."

rm -f swap
exit 0
