#!/bin/bash

sudo apt install bzip2 git vim make gcc libncurses-dev flex bison bc cpio libelf-dev libssl-dev syslinux dosfstools -y -qqq
wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.18.9.tar.xz
tar xf linux-6.18.9.tar.xz
cd linux-6.18.9
make olddefconfig
sed -i 's/^CONFIG_LOCALVERSION=".*"/CONFIG_LOCALVERSION="-pardus25-amd64"/' .config
make -j$(nproc)
sudo make modules_install 
sudo make install
sudo update-grub
sudo update-initramfs -c -k 6.18.9-pardus25-amd64

sudo apt remove --autoremove --purge linux-image-6.12.57+deb13-amd64
sudo apt remove --autoremove --purge linux-image-6.12.63+deb13-amd64

echo "Kernel has been swapped succesfully | Çekirdek başarıyla değiştirildi."

exit 0
